<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>our App</title>
	<meta name="description" content="A free html template with Sketch design made with Bootstrap">
	<meta name="keywords" content="free html template, bootstrap, ui kit, sass" />
	<meta name="author" content="Codrops" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- favicon generated by http://realfavicongenerator.net/ -->
	
	<meta name="msapplication-TileColor" content="#66e0e5">
	<meta name="msapplication-TileImage" content="img/favicon/mstile-144x144.png">
	<meta name="msapplication-config" content="img/favicon/browserconfig.xml">
	<meta name="theme-color" content="#ffffff">
	<!-- end favicon links -->
	 

	<link  href="<?php echo base_url();?>/assets/css/bootstrap.min.css" rel="stylesheet"/>
	<link  href="<?php echo base_url();?>/assets/css/normalize.min.css" rel="stylesheet">
	<link  href="<?php echo base_url();?>/assets/css/animate.min.css" rel="stylesheet">
	<link  href="<?php echo base_url();?>/assets/css/flickity.min.css" rel="stylesheet">
	<link  href="<?php echo base_url();?>/assets/css/styles.css" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">


	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js"></script>
	<script src="http://vjs.zencdn.net/5.4.6/video.min.js"></script>
	<!-- jQuery local fallback -->
	<script>
	//window.jQuery || document.write('<script src="js/min/jquery-1.11.2.min.js"><\/script>')
	</script>
	<!-- JS Locals -->

	<script src="<?php echo base_url();?>/assets/js/min/bootstrap.min.js"></script>
	<script src="<?php echo base_url();?>/assets/js/min/modernizr-2.8.3-respond-1.4.2.min.js"></script>
	<script src="<?php echo base_url();?>/assets/js/min/retina.min.js"></script>
	<script src="<?php echo base_url();?>/assets/js/min/jquery.waypoints.min.js"></script>
	<script src="<?php echo base_url();?>/assets/js/min/flickity.pkgd.min.js"></script>
	<script src="<?php echo base_url();?>/assets/js/min/scripts-min.js"></script>
</head>